apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: service-a
        image: djhope99/service-a:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: service-b
        image: djhope99/service-b:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: service-c
        image: djhope99/service-c:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: load-generator
        image: djhope99/load-generator:latest
        env:
        - name: REQUEST_RATE_MS
          value: "1000"  # Adjust request rate here (milliseconds) 