apiVersion: v1
kind: Service
metadata:
  name: service-a-svc
spec:
  selector:
    app: service-a
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-svc
spec:
  selector:
    app: service-b
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-c-svc
spec:
  selector:
    app: service-c
  ports:
  - port: 8080
    targetPort: 8080 